# This configuration spins up a client with dummy sensors and publishes via MQTT
# Ideal for testing on a laptop :)

EventSinks:
    - MQTTEventSink:
        class: "mqtt_event_sink.MQTTEventSink"
        hostname: "mqtt2.m2m4connectedlife.com"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        password: null
        keepalive: 60
        #need to insert address before using: topic: "iot-1/d/%012x/evt/%s/json"
    - RelayEventSink:
        class: "relay_event_sink.RelayEventSink"
        relay_port: 3868
        scan_interval: 5 # every hour
        refresh_socket_conns: 600 # every 10 min

Applications:
    - Thread:
        class: "dummy_threaded_application.DummyThreadedApplication"
    - MeshRelayedEventReceiver:
        class: "mesh_relayed_event_receiver.MeshRelayedEventReceiver"
    - LocationManager:
        class: "location_manager.LocationManager"

Sensors:
    - HBSensor:
        class: "heartbeat_virtual_sensor.HeartbeatVirtualSensor"
        dev_name: "hb0"
        interval: 60
    - DummyPIRSensor:
        class: "dummy_sensors.dummy_pir_virtual_sensor.DummyPIRVirtualSensor"
        dev_name: "pir0"
    - DummyLightSensor:
        class: "dummy_sensors.dummy_light_virtual_sensor.DummyLightVirtualSensor"
        dev_name: "light0"
    - DummyGasSensor:
        class: "dummy_sensors.dummy_gas_virtual_sensor.DummyGasVirtualSensor"
        dev_name: "gas0"
    - DummyTempSensor:
        class: "dummy_sensors.dummy_temperature_virtual_sensor.DummyTemperatureVirtualSensor"
        dev_name: "cel0"
    - DummySeismicSensor:
        class: "dummy_sensors.dummy_csn_virtual_sensor.DummyCSNVirtualSensor"
        dev_name: "accel0"
    - GeoIPSensor:
        class: "location_sensors.geo_ip_virtual_sensor.GeoIPVirtualSensor"
        dev_name: "geoip0"
    - InternetAccessSensor:
        class: "internet_access_virtual_sensor.InternetAccessVirtualSensor"
        dev_name: "net0"
    - PIRNoMotionSensor:
        class: "pir_no_motion_virtual_sensor.PIRNoMotionVirtualSensor"
        dev_name: "nomot0"
    - LightFlashSensor:
        class: "light_flash_virtual_sensor.LightFlashVirtualSensor"
        dev_name: "flash0"
    - TempHighSensor:
        class: "temperature_high_virtual_sensor.TemperatureHighVirtualSensor"
        dev_name: "heat0"

Networks:
    - NetworkManager:
        class: "scale_network_manager.ScaleNetworkManager"
        batman_interface: "wlan0:avahi"
        batman_originators_file: "/sys/kernel/debug/batman_adv/bat0/originators"
