# New features have been added to Raspberry Pi based SCALE boxes in May, 2015
# This configruration is created to keep the original one unchange,
#   in order not to mess up with old devices
# Copy this file to /etc/scale/client/config.yml for configuration overriding
# Should be merged into pi_config.yml after ALL devices are made up-to-date

Main:
    event_queue_size: 4096

EventSinks:
    - MQTTPublisher:
        class: "mqtt_event_sink.MQTTEventSink"
        hostname: "dime.smartamerica.io"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        password: null
        keepalive: 60
    - MySQLDatabase:
        class: "mysql_event_sink.MySQLEventSink"
        dbname: "scale_client"
        username: "scale_usr"
        password: "123456"
    #- SigfoxPublisher:
    #    class: "sigfox_event_sink.SigfoxEventSink"
    #    serialport: "/dev/ttyUSB0"

Applications:
    - LocationManager:
        class: "location_manager.LocationManager"
    - MySQLDatabase:
        class: "mysql_maintainer.MySQLMaintainer"
        dbname: "scale_client"
        username: "scale_usr"
        password: "123456"

Sensors:
    - HBSensor:
        class: "heartbeat_virtual_sensor.HeartbeatVirtualSensor"
        dev_name: "hb0"
        interval: 60
    - PIRSensor:
        class: "pir_virtual_sensor.PIRVirtualSensor"
        dev_name: "pir0"
        gpio_pin: 17
    - LightSensor:
        class: "light_virtual_sensor.LightVirtualSensor"
        dev_name: "light0"
        analog_port: 3
    - GasSensor:
        class: "gas_virtual_sensor.GasVirtualSensor"
        dev_name: "gas0"
        analog_port: 0
    #- RawAnalogSensor:
    #    class: "raw_analog_virtual_sensor.RawAnalogVirtualSensor"
    #    dev_name: "raw0"
    #    analog_port: 2
    - GeoIPSensor:
        class: "location_sensors.geo_ip_virtual_sensor.GeoIPVirtualSensor"
        dev_name: "geoip0"
    - InternetAccessSensor:
        class: "internet_access_virtual_sensor.InternetAccessVirtualSensor"
        dev_name: "net0"
    - PIRNoMotionSensor:
        class: "pir_no_motion_virtual_sensor.PIRNoMotionVirtualSensor"
        dev_name: "nomot0"
    - LightFlashSensor:
        class: "light_flash_virtual_sensor.LightFlashVirtualSensor"
        dev_name: "flash0"
    - TemperatureSensor:
        class: "temperature_virtual_sensor.TemperatureVirtualSensor"
        dev_name: "cel0"
    - TemperatureHighSensor:
        class: "temperature_high_virtual_sensor.TemperatureHighVirtualSensor"
        dev_name: "heat0"

